### ISSUE TITLE
marking room after rejoining server throws NPE

### ISSUE THREAD

**Issue by radimous** [NodiumHosting/VaultMapper#5]
VaultMap#getCurrentCell returns null, so you can't access the fields
https://github.com/NodiumHosting/VaultMapper/blob/80c152db847e1e422c374e46b19beef7e752ec9a/src/main/java/com/nodiumhosting/vaultmapper/map/VaultMap.java#L251

**Comment by Anorak01** [comment]
Just to indicate that the issue has been read and noted, thank you for the report.
We'll see when we can fix it, but it will likely be a part of larger update later.

**Comment by McMelonTV** [comment]
Fixed in v1.5.2
